apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argo-pvc
  namespace: argocd
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
